rule get_annotation:
    output:
        "refs/annotation.gtf.gz"
    params:
        species="homo_sapiens",
        release="98",
        build="GRCh38",
        fmt="gtf"
    wrapper:
        "file:/home/fritjof/code/snakemake-wrappers/bio/reference/ensembl-annotation"
